#!/bin/bash


##############################################
#                   __ _             _       #
#   ___ ___  _ __  / _(_) __ _   ___| |__    #
#  / __/ _ \| '_ \| |_| |/ _` | / __| '_ \   #
# | (_| (_) | | | |  _| | (_| |_\__ \ | | |  #
#  \___\___/|_| |_|_| |_|\__, (_)___/_| |_|  #
#                        |___/               #
#                                            #
#               guanglaihe@gmail.com         #
#               config script in Manjaro     #
#               Create: 2019-09-03           #
#               Update: 2019-09-03           #
##############################################

root_dir="$(pwd)"
function conf {
    cd $cfg_dir
    ./config
    cd $root_dir
}

# code
cfg_dir="$(pwd)/code/linux"; conf;
# i3wm
cfg_dir="$(pwd)/i3wm"; conf;
# zsh
cfg_dir="$(pwd)/zsh"; conf;
# nvim
cfg_dir="$(pwd)/nvim"; conf;
# tmux
cfg_dir="$(pwd)/tmux"; conf;
# scripts
cfg_dir="$(pwd)/scripts"; conf;
# misc
cfg_dir="$(pwd)/misc"; conf;

