#!/bin/bash

softlink="../softlink-config"
# i3 config file
$softlink "$HOME/.config/i3" "config" "i3/i3config"
# i3exit
$softlink "$HOME/bin" "i3exit" "i3/i3exit.sh"
# polybar config file
$softlink "$HOME/.config/polybar" "config" "polybar/pbconfig"
# polybar launch shell script
$softlink "$HOME/bin" "polybar-launch" "polybar/polybar-launch"
# dunct
$softlink "$HOME/.config/dunst" "dunstrc" "dunstrc"
# compton
$softlink "$HOME/.config" "compton.conf" "compton.conf"
# i3-scrot
$softlink "$HOME/.config" "i3-scrot.conf" "i3-scrot.conf"
# profile
$softlink "$HOME" ".profile" "profile"
# xfce4-terminal
$softlink "$HOME/.config/xfce4/terminal" "terminalrc" "terminalrc"
# Xmodmap
$softlink "$HOME" ".Xmodmap" "Xmodmap"

