#!/usr/bin/bash

cat <<-"EOF"
        _                       __           
 _   __(_)___ ___        ____  / /_  ______ _
| | / / / __ `__ \______/ __ \/ / / / / __ `/
| |/ / / / / / / /_____/ /_/ / / /_/ / /_/ / 
|___/_/_/ /_/ /_/     / .___/_/\__,_/\__, /  
                     /_/            /____/   

EOF

PLUG_VIM='$HOME/.local/share/nvim/site/autoload/plug.vim'
if [ ! -e "$PLUG_VIM" ]; then
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

./done

