#!/usr/bin/bash

hasHDMI=`xrandr | grep "HDMI1 connected"`
if [ -z "$hasHDMI" ]; then
    xrandr --output HDMI1 --off --output eDP1 --auto
    pacmd set-card-profile 0 output:analog-stereo
else
    xrandr --output HDMI1 --auto --output eDP1 --off
    pacmd set-card-profile 0 output:hdmi-stereo
fi

