#!/usr/bin/bash

# install third part oh-my-zsh plugin
ZSH_CUSTOM_PLUGINS="$HOME/.oh-my-zsh/custom/plugins"
function install_github_plugin {
    plugin="$ZSH_CUSTOM_PLUGINS/$plugin_name"
    if [ ! -d $plugin ]; then
        git clone "$remote_plugin" "$plugin"
    else
        echo "$plugin_name has been installed"
    fi
}

# zsh autosuggestions
plugin_name="zsh-autosuggestions"
remote_plugin="https://github.com/zsh-users/zsh-autosuggestions"
install_github_plugin

# zsh syntax highlighting
plugin_name="zsh-syntax-highlighting"
remote_plugin="zsh-users/zsh-syntax-highlighting"
install_github_plugin

