# If you come from bash you might have to change your $PATH.
export PATH="$HOME/.gem/ruby/2.6.0/bin:$HOME/bin:/usr/local/bin:$PATH"

if [ -d "$HOME/Applications" ]; then
    export PATH=$HOME/Applications:$PATH
fi

if [ -d "$HOME/.gem/ruby/2.5.0/bin" ]; then
    export PATH=$HOME/.gem/ruby/2.5.0/bin:$PATH
fi

if [ -d "$HOME/bin/geckodriver" ]; then
    export PATH=$HOME/bin/geckodriver:$PATH
fi

# export ALL_PROXY=socks5://127.0.0.1:1080

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="agnosterzak"
ZSH_THEME="nametime"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    zsh-syntax-highlighting
    zsh-autosuggestions
    colored-man-pages
    archlinux
    extract
    tmux
    git
    wd
    z
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
# env "LC_CTYPE=zh_CN.UTF-8" emacs

# Preferred editor
export EDITOR='nvim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# colors
if [ -f $HOME/.dir_colors ]; then
    eval `dircolors $HOME/.dir_colors`
fi

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias zshconfig="$EDITOR $HOME/.zshrc"
alias ohmyzshconfig="$EDITOR $HOME/.oh-my-zsh"

# neovim alias
if type nvim > /dev/null 2>&1; then
    alias less='/usr/share/nvim/runtime/macros/less.sh'
    alias viconfig="$EDITOR ~/.config/nvim/init.vim"
fi

if type musicbox > /dev/null 2>&1; then
    alias music='musicbox'
fi

# if type leetcode > /dev/null 2>&1; then
    alias lc='leetcode'
    alias plc='proxychains4 leetcode'
    alias lcshow='leetcode show -gxe'
# fi

if type i3 > /dev/null 2>&1; then
    alias i3config="$EDITOR $HOME/.config/i3/config"
fi

if type polybar > /dev/null 2>&1; then
    alias pbconfig="$EDITOR $HOME/.config/polybar/config"
fi

if type exa > /dev/null 2>&1; then
    alias e='exa'
fi

if type xsel > /dev/null 2>&1; then
    alias clip='xsel -b'
fi

if type trash > /dev/null 2>&1; then
    alias trm='trash'
    alias tre='trash-restore'
    alias tls='trash-list'
fi

alias pc='proxychains4'

alias bc='bc -l'
alias c='clear'
alias today='date +%Y-%m-%d'
alias tmuxconfig="$EDITOR $HOME/.tmux.conf"
alias say='fortune | cowsay | lolcat'
alias emacs='emacs -nw'

alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../'
alias .5='cd ../../../../'

alias mv=' timeout 8 mv -iv'
alias rm=' noglob timeout 3 rm -Iv --one-file-system'

alias ojn='ojn.sh'
alias marktext='flatpak run com.github.marktext.marktext'
alias zathura='nohup zathura'

# nvm for nvim
if [ -f /usr/share/nvm/init-nvm.sh ]; then
    source /usr/share/nvm/init-nvm.sh
fi

alias setproxy="export ALL_PROXY=socks5://127.0.0.1:1080"
alias unsetproxy="unset ALL_PROXY"

alias ipy='ipython'

# size of saved history
HISTSIZE=100000
SAVEHIST=100000
